title: Jacopo Nardiello
url: http://jnardiello.github.io

author:
    name: Jacopo Nardiello
    uri: http://jnardiello.github.io

timezone: UTC
markdown: redcarpet
pygments: true


kramdown:
    input: GFM