title: Jacopo Nardiello
url: http://jnardiello.github.io

author:
    name: Jacopo Nardiello
    description: Programmer and DevOps. Founder <a href="http://sighup.io" class="sighup">SIGHUP</a>. Mostly Cloud-Native infrastructures, Golang, Kubernetes and containers.
    twitter: jnardiello
    github: jnardiello
    linkedin: jnardiello

timezone: UTC
markdown: kramdown
highlighter: rouge
host:    0.0.0.0

permalink: /:title.html

kramdown:
    input: GFM
exclude: [makefile]
