title: Cloud-Native, Kubernetes, Entrepreneurship
description: Jacopo Nardiello's personal blog. Strategic thinking and Technical articles about Kubernetes, Cloud Native, DevOps practices and Entrepreneurship.
url: https://jnardiello.me

author:
    name: Jacopo Nardiello
    description: Founder <a href="https://sighup.io" class="sighup">@SIGHUP</a>. Programmer and DevOps.<br /> Mostly Cloud-Native infrastructures, Kubernetes, Containers and Entrepreneurship.
    twitter: 
      name: "@jnardiello"
      url: https://twitter.com/jnardiello
    github: 
      name: github/jnardiello
      url: https://github.com/jnardiello
    linkedin: 
      name: linkedin/jnardiello
      url: https://www.linkedin.com/in/jnardiello/

timezone: UTC
markdown: kramdown
highlighter: rouge
host:    0.0.0.0

permalink: /:title.html

kramdown:
    input: GFM
exclude: [makefile]

plugins:
  - jekyll-sitemap
  - jekyll-feed
