title: "Jacopo Nardiello's personal blog: Cloud, Infrastructure and AI Automation, Kubernetes, Entrepreneurship"
description: "Jacopo Nardiello's personal blog. Strategic thinking, Technical articles about Kubernetes, Cloud Technologies, AI Automation and Entrepreneurship."
url: "https://jnardiello.me"
baseurl: ""

author:
    name: Jacopo Nardiello
    description: Technologist. Open source. Building the next generation of the enterprise. Introvert who speaks at conferences. Founder who still writes code.
    x:
      name: "x/jnardiello"
      url: https://x.com/jnardiello
    github:
      name: github/jnardiello
      url: https://github.com/jnardiello
    linkedin:
      name: linkedin/jnardiello
      url: https://www.linkedin.com/in/jnardiello/
    bluesky:
      name: bluesky/jnardiello
      url: https://bsky.app/profile/jnardiello.bsky.social

timezone: UTC
markdown: kramdown
highlighter: rouge
host: 0.0.0.0

permalink: /:title.html
paginate: 20
paginate_path: "/page:num/"

kramdown:
    input: GFM
exclude:
  - makefile
  - README.md
  - "jnardiello.me redesign.zip"
  - vendor

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
