title: Jacopo Nardiello
url: http://jnardiello.github.io

author:
    name: Jacopo Nardiello
    description: Programmer. Most of the time i play around with Data. I love Zen and OSS. Try to keep the good parts of XP and 5S methodologies.
    twitter: jnardiello
    github: jnardiello
    linkedin: jnardiello

timezone: UTC
markdown: redcarpet
pygments: true

permalink: /:title.html

kramdown:
    input: GFM
