title: Jacopo Nardiello
url: http://jnardiello.github.io

author:
    name: Jacopo Nardiello
    description: Programmer and Computer Scientist. Data enthusiast. I love Zen, XP and 5S methodologies.
    twitter: jnardiello
    github: jnardiello
    linkedin: jnardiello

timezone: UTC
markdown: redcarpet
pygments: true

permalink: /:title.html

kramdown:
    input: GFM
