title: Jacopo Nardiello
url: http://jnardiello.github.io

author:
    name: Jacopo Nardiello
    description: Programmer. Mostly playing around with data. I love Zen, XP and 5S Methodologies.
    description: Programmer and DevOps, founder @SIGHUP. Cloud-Native infrastructures. Golang, Kubernetes and containers. I make the cloud.
    twitter: jnardiello
    github: jnardiello
    linkedin: jnardiello

timezone: UTC
markdown: kramdown
highlighter: rouge
host:    0.0.0.0

permalink: /:title.html

kramdown:
    input: GFM
exclude: [makefile]
